"""Create Ride & relate to User

Revision ID: d592334ef492
Revises: 0d789718a12c
Create Date: 2021-07-31 07:02:32.730688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd592334ef492'
down_revision = '0d789718a12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=15), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('town_from', sa.String(length=80), nullable=False),
    sa.Column('town_to', sa.String(length=80), nullable=False),
    sa.Column('depart_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride')
    # ### end Alembic commands ###
