"""Create RideRequest table & relationships

Revision ID: f8be9caafd66
Revises: d592334ef492
Create Date: 2021-08-19 16:07:51.217261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8be9caafd66'
down_revision = 'd592334ef492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('stop', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('made_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ride_request')
    # ### end Alembic commands ###
