"""add passenger names and audit logs

Revision ID: 6b7868552c83
Revises: e12bfc41339e
Create Date: 2026-08-19 21:00:59.953223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7868552c83'
down_revision: Union[str, None] = 'e12bfc41339e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rideRequests', sa.Column('passenger_names', sa.String(), nullable=True))
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('entity_type', sa.String(length=20), nullable=False),
        sa.Column('entity_uuid', sa.String(length=36), nullable=False),
        sa.Column('action', sa.String(length=40), nullable=False),
        sa.Column('changes', sa.String(), nullable=True),
        sa.Column('actor_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index('ix_audit_logs_entity_uuid', 'audit_logs', ['entity_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_entity_uuid', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_column('rideRequests', 'passenger_names')
    # ### end Alembic commands ###
