"""Add uuid to user rides and rideRequests

Revision ID: 98fc1f4c8413
Revises: cb6e1d816d97
Create Date: 2024-12-03 15:50:11.585912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fc1f4c8413'
down_revision: Union[str, None] = 'cb6e1d816d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rideRequests', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'rideRequests', ['uuid'])
    op.add_column('rides', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'rides', ['uuid'])
    op.add_column('users', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'users', ['uuid'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'uuid')
    op.drop_constraint(None, 'rides', type_='unique')
    op.drop_column('rides', 'uuid')
    op.drop_constraint(None, 'rideRequests', type_='unique')
    op.drop_column('rideRequests', 'uuid')
    # ### end Alembic commands ###
