"""Add pickup field to the ride requests

Revision ID: e12bfc41339e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-17 14:20:35.422841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12bfc41339e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rideRequests', sa.Column('pickup', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rideRequests', 'pickup')
    # ### end Alembic commands ###
